image: python:3.10

stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - pip install pytest flake8

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

code-quality-job:
  stage: lint
  script:
    - echo "Running code quality checks..."
    - flake8 .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
